version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mindlogger_mongo
    volumes:
      - db_data:/data/db
      - /tmp/:/tmp/

volumes:
  db_data: {}
